package com.gestion.utils;

public enum Actions {
    CREAR_USUARIO,ELIMINAR_USUARIO,MODIFICAR_ROL,BUSCAR_USUARIO,IMPRIMIR_HISTORIA,ACTUALIZAR_CONTRASEÑA,ACTUALIZAR_NOMBRE, IMPRIMIR_HISTORIAL_COMPLETO;
}
